// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: transfer.sql

package db

import (
	"awesomeProject1/util"
	"context"
	"github.com/stretchr/testify/require"
	"testing"
	"time"
)

func TestQueries_CreateTransfer(t *testing.T) {
	randomAccount1 := createRandomAccount(t)
	randomAccount2 := createRandomAccount(t)
	createRandomTransfer(t, randomAccount1, randomAccount2)
}

func TestQueries_GetTransfer(t *testing.T) {
	account1 := createRandomAccount(t)
	account2 := createRandomAccount(t)
	transfer1 := createRandomTransfer(t, account1, account2)

	transfer2, err := testQueries.GetTransfer(context.Background(), transfer1.ID)
	require.NoError(t, err)
	require.NotEmpty(t, transfer2)

	require.Equal(t, transfer1.ID, transfer2.ID)
	require.Equal(t, transfer1.FromAccountID, transfer2.FromAccountID)
	require.Equal(t, transfer1.ToAccountID, transfer2.ToAccountID)
	require.Equal(t, transfer1.Amount, transfer2.Amount)
	require.WithinDuration(t, transfer1.CreatedAt, transfer2.CreatedAt, time.Second)
}

func TestQueries_ListTransfers(t *testing.T) {
	randomAccount1 := createRandomAccount(t)
	randomAccount2 := createRandomAccount(t)

	for i := 0; i < 10; i++ {
		createRandomTransfer(t, randomAccount1, randomAccount2)
	}

	params := ListTransfersParams{
		FromAccountID: randomAccount1.ID,
		ToAccountID:   randomAccount2.ID,
		Limit:         5,
		Offset:        5,
	}

	transfers, err := testQueries.ListTransfers(context.Background(), params)
	require.Len(t, transfers, 5)
	require.NoError(t, err)
	for _, transfer := range transfers {
		require.NotEmpty(t, transfer)
	}

}

func createRandomTransfer(t *testing.T, account1 Account, account2 Account) Transfer {
	arg := CreateTransferParams{
		FromAccountID: account1.ID,
		ToAccountID:   account2.ID,
		Amount:        util.RandomMoney(),
	}
	transfer, err := testQueries.CreateTransfer(context.Background(), arg)
	require.NoError(t, err)
	require.NotEmpty(t, transfer)

	require.Equal(t, arg.FromAccountID, transfer.FromAccountID)
	require.Equal(t, arg.ToAccountID, transfer.ToAccountID)
	require.Equal(t, arg.Amount, transfer.Amount)

	require.NotZero(t, transfer.ID)
	require.NotZero(t, transfer.CreatedAt)

	return transfer

}
